apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:cluster-manager-placement:reader
rules:
# Allow controller to get/list/watch configmaps
- apiGroups: [""]
  resources: ["configmaps", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list"]
# Allow controller to view managedclusters/managedclustersets/managedclustersetbindings
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["managedclusters", "managedclustersets", "managedclustersetbindings"]
  verbs: ["get", "list", "watch"]
# Allow controller to view addonplacementscores
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["addonplacementscores"]
  verbs: ["get", "list", "watch"]
# Allow controller to get/list/watch placements/placementdecisions
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["placements"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["placementdecisions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["placements/status", "placementdecisions/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cluster.open-cluster-management.io"]
  resources: ["placements/finalizers"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:cluster-manager-placement:reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:cluster-manager-placement:reader
subjects:
- kind: ServiceAccount
  namespace: argocd
  name: argocd-applicationset-controller
